// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go

// Package mocks is a generated GoMock package.
package mocks

import (
	entity "API-quest-answ/internal/entity"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAnswersRepo is a mock of AnswersRepo interface.
type MockAnswersRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAnswersRepoMockRecorder
}

// MockAnswersRepoMockRecorder is the mock recorder for MockAnswersRepo.
type MockAnswersRepoMockRecorder struct {
	mock *MockAnswersRepo
}

// NewMockAnswersRepo creates a new mock instance.
func NewMockAnswersRepo(ctrl *gomock.Controller) *MockAnswersRepo {
	mock := &MockAnswersRepo{ctrl: ctrl}
	mock.recorder = &MockAnswersRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnswersRepo) EXPECT() *MockAnswersRepoMockRecorder {
	return m.recorder
}

// CreateAnswer mocks base method.
func (m *MockAnswersRepo) CreateAnswer(ctx context.Context, answer *entity.Answer) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAnswer", ctx, answer)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAnswer indicates an expected call of CreateAnswer.
func (mr *MockAnswersRepoMockRecorder) CreateAnswer(ctx, answer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAnswer", reflect.TypeOf((*MockAnswersRepo)(nil).CreateAnswer), ctx, answer)
}

// DeleteAnswer mocks base method.
func (m *MockAnswersRepo) DeleteAnswer(ctx context.Context, id int64, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAnswer", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAnswer indicates an expected call of DeleteAnswer.
func (mr *MockAnswersRepoMockRecorder) DeleteAnswer(ctx, id, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAnswer", reflect.TypeOf((*MockAnswersRepo)(nil).DeleteAnswer), ctx, id, userID)
}

// GetAllByQuestionID mocks base method.
func (m *MockAnswersRepo) GetAllByQuestionID(ctx context.Context, questionID int64) ([]*entity.Answer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllByQuestionID", ctx, questionID)
	ret0, _ := ret[0].([]*entity.Answer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllByQuestionID indicates an expected call of GetAllByQuestionID.
func (mr *MockAnswersRepoMockRecorder) GetAllByQuestionID(ctx, questionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllByQuestionID", reflect.TypeOf((*MockAnswersRepo)(nil).GetAllByQuestionID), ctx, questionID)
}

// GetAnswerByID mocks base method.
func (m *MockAnswersRepo) GetAnswerByID(ctx context.Context, id int64) (*entity.Answer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAnswerByID", ctx, id)
	ret0, _ := ret[0].(*entity.Answer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAnswerByID indicates an expected call of GetAnswerByID.
func (mr *MockAnswersRepoMockRecorder) GetAnswerByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnswerByID", reflect.TypeOf((*MockAnswersRepo)(nil).GetAnswerByID), ctx, id)
}
