// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/PANDA-1703/API-questions-and-answers/internal/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockAnswersRepo is a mock of AnswersRepo interface.
type MockAnswersRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAnswersRepoMockRecorder
}

// MockAnswersRepoMockRecorder is the mock recorder for MockAnswersRepo.
type MockAnswersRepoMockRecorder struct {
	mock *MockAnswersRepo
}

// NewMockAnswersRepo creates a new mock instance.
func NewMockAnswersRepo(ctrl *gomock.Controller) *MockAnswersRepo {
	mock := &MockAnswersRepo{ctrl: ctrl}
	mock.recorder = &MockAnswersRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnswersRepo) EXPECT() *MockAnswersRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAnswersRepo) Create(ctx context.Context, answer *entity.Answer) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, answer)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAnswersRepoMockRecorder) Create(ctx, answer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAnswersRepo)(nil).Create), ctx, answer)
}

// Delete mocks base method.
func (m *MockAnswersRepo) Delete(ctx context.Context, id int64, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAnswersRepoMockRecorder) Delete(ctx, id, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAnswersRepo)(nil).Delete), ctx, id, userID)
}

// GetAllByQuestionID mocks base method.
func (m *MockAnswersRepo) GetAllByQuestionID(ctx context.Context, questionID int64) ([]*entity.Answer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllByQuestionID", ctx, questionID)
	ret0, _ := ret[0].([]*entity.Answer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllByQuestionID indicates an expected call of GetAllByQuestionID.
func (mr *MockAnswersRepoMockRecorder) GetAllByQuestionID(ctx, questionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllByQuestionID", reflect.TypeOf((*MockAnswersRepo)(nil).GetAllByQuestionID), ctx, questionID)
}

// GetByID mocks base method.
func (m *MockAnswersRepo) GetByID(ctx context.Context, id int64) (*entity.Answer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Answer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAnswersRepoMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAnswersRepo)(nil).GetByID), ctx, id)
}
