// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/PANDA-1703/API-questions-and-answers/internal/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockQuestionsRepo is a mock of QuestionsRepo interface.
type MockQuestionsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockQuestionsRepoMockRecorder
}

// MockQuestionsRepoMockRecorder is the mock recorder for MockQuestionsRepo.
type MockQuestionsRepoMockRecorder struct {
	mock *MockQuestionsRepo
}

// NewMockQuestionsRepo creates a new mock instance.
func NewMockQuestionsRepo(ctrl *gomock.Controller) *MockQuestionsRepo {
	mock := &MockQuestionsRepo{ctrl: ctrl}
	mock.recorder = &MockQuestionsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuestionsRepo) EXPECT() *MockQuestionsRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockQuestionsRepo) Create(ctx context.Context, question *entity.Question) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, question)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockQuestionsRepoMockRecorder) Create(ctx, question interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockQuestionsRepo)(nil).Create), ctx, question)
}

// Delete mocks base method.
func (m *MockQuestionsRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockQuestionsRepoMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockQuestionsRepo)(nil).Delete), ctx, id)
}

// GetAll mocks base method.
func (m *MockQuestionsRepo) GetAll(ctx context.Context) ([]*entity.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]*entity.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockQuestionsRepoMockRecorder) GetAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockQuestionsRepo)(nil).GetAll), ctx)
}

// GetByID mocks base method.
func (m *MockQuestionsRepo) GetByID(ctx context.Context, id int64) (*entity.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockQuestionsRepoMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockQuestionsRepo)(nil).GetByID), ctx, id)
}
